### PR TITLE
Add Algolia search

### LINKED ISSUE #200: Documentation searching
We miss search capability in docs, Docusaurus provides such ability https://docusaurus.io/docs/en/search. Should be way easier to find certain piece of content than clicking around.

### LINKED ISSUE #212: Update docusaurus to v1.9

### PR DESCRIPTION
**Pull request by pavestru**
## Description

Closes #200 
Closes #212 

## What to look out for

Dear reviewer, I want you to

- `cd website` and `yarn start`
- Watch out: The links generated by Algolia point to absolute paths starting with accenture.github.io instead of localhost:3000

### CODE REVIEW

**Comment by pavestru** [comment]
Do you think I should also improve the styles of search input? I don't like it.

Compare this
Screen Shot 2019-04-30 at 00 42 12
with the one on [Docusaurus](https://docusaurus.io).

**Comment by mmacai** [comment]
> Do you think I should also improve the styles of search input? I don't like it.
> 
> Compare this
> Screen Shot 2019-04-30 at 00 42 12
> with the one on [Docusaurus](https://docusaurus.io).

Ye, looks a bit misplaced - imo why not, but we should consider if e.g. Docusaurus version update won't brake the styles (somehow).

**Comment by kevinbader** [comment]
you could compare our config with https://github.com/facebook/Docusaurus/tree/master/website

**Comment by pavestru** [comment]
yeah, Docusaurus' docusaurus seems to be 2.0.0-alpha

**Comment by pavestru** [comment]
I've updated Docusaurus' minor version (to 1.9.0) and it looks much better now:
Screen Shot 2019-04-30 at 23 06 05

**Comment by pavestru** [comment]
I have also removed website/package-lock.json due to yarn.lock being newer and this warning:
```
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
```

**Comment by kevinbader** [comment]
> I've updated Docusaurus' minor version (to 1.9.0)

Thanks, I've updated your description to close the related issue.

> I have also removed website/package-lock.json

Is there any reason to use yarn over npm these days?

**Comment by pavestru** [comment]
> Is there any reason to use yarn over npm these days?

No, I don't think so. Yarn is just a bit faster and has some specific features we are not using here. It's just a matter of taste (preference), I think.

**Pull request merged**
