### PR TITLE
277 proxy validation

### LINKED ISSUE #277: Improve validation for reverse proxy configuration
The reverse proxy configuration should be validated
- when loading it from a configuration file / environment variable,
- when using the API.

For example, when creating a route with target `kinesis` without a target topic, and the variable `PROXY_KINESIS_REQUEST_STREAM` is not set, loading the configuration should fail. Currently, the configuration will be applied but clients will see an error once they try to use the route.

If an error is encountered:
- If the configuration passed on startup contains an error, RIG should refuse to start.
- If the configuration passed to RIG's API contains as error, RIG should respond with an 400 Bad Request status code.

### PR DESCRIPTION
**Pull request by mmacai**
## Description

Added reverse proxy configuration to do initial check when RIG starts and for REST API.

Closes #277 

## What to look out for

Dear reviewer, I want you to

- check the way how validation works - if it makes sense or you would do it differently
- check the way how errors look like
- check covered scenarios
- unit tests should cover all use cases
- you can test it also manually:

```json
[{
  "id": "kafka-service",
  "name": "kafka-service",
  "versioned": false,
  "version_data": {
    "default": {
      "endpoints": [
        {
          "id": "post-async-publish",
          "path": "/kafka/async-publish",
          "method": "POST",
          "target": "kafka"
        }
      ]
    }
  },
  "proxy": {
    "use_env": true,
    "target_url": "KAFKA_HOST",
    "port": 9092
  }
}]
```

These should kill the RIG:

```bash
PROXY_CONFIG_FILE=./proxy.json mix phx.server
# cross check that it's not satisfied with Kinesis settings
PROXY_CONFIG_FILE=./proxy.json PROXY_KINESIS_REQUEST_STREAM=haha mix phx.server
```

This should be ok:

```bash
PROXY_CONFIG_FILE=./proxy.json PROXY_KAFKA_REQUEST_TOPIC=haha mix phx.server
# or add topic: "haha" to json and simply run
PROXY_CONFIG_FILE=./proxy.json mix phx.server
```

## Process

Have fun!

### CODE REVIEW

**Comment by kevinbader** [comment]
```bash
$ PROXY_CONFIG_FILE='{}' mix phx.server
...
13:14:32.063 module=gen_server [error] GenServer RigInboundGateway.Proxy terminating
** (MatchError) no match of right hand side value: {:error, "the proxy config must be a list", [not_a_list: %{}]}
    (rig 2.3.0) lib/rig_inbound_gateway/proxy.ex:140: RigInboundGateway.Proxy.handle_info/2
    (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :init_apis
State: %{tracker_mod: RigInboundGateway.ApiProxy.Tracker}
```

but keeps running - I've expected RIG to halt here. Same when using a file that doesn't exist:

```bash
$ PROXY_CONFIG_FILE=./doesnotexist.json mix phx.server
...
13:21:26.703 module=gen_server [error] GenServer RigInboundGateway.Proxy terminating
** (MatchError) no match of right hand side value: {:error, "could not read proxy config", [syntax_error: [{:not_found, "./proxy.json"}, %Jason.DecodeError{data: "./proxy.json", position: 0, token: nil}], path_or_json: "./proxy.json"]}
    (rig 2.3.0) lib/rig_inbound_gateway/proxy.ex:140: RigInboundGateway.Proxy.handle_info/2
    (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :init_apis
State: %{tracker_mod: RigInboundGateway.ApiProxy.Tracker}
```

Doesn't halt...

---

`version_data.default.endpoints` should be a list. However, when using an object instead, there are no errors reported:

```bash
$ PROXY_CONFIG_FILE='[{"id":"a","name":"a","proxy":{"target_url":"KAFKA_HOST","use_env":true,"port":9092},"version_data":{"default":{"endpoints":{}}}}]' mix phx.server
...
13:29:45.584 module=RigInboundGateway.ApiProxy.Tracker [info] Starting to track new API definition with id=a
...
```

---

The HTTP method shouldn't be parsed in a case-sensitive way. For example, this runs without warnings but doesn't work as expected:

```bash
PROXY_CONFIG_FILE='[{"id":"a","name":"a","proxy":{"target_url":"KAFKA_HOST","use_env":true,"port":9092},"version_data":{"default":{"endpoints":[{"id":"x","path":"/x","method":"get"}]}}}]' mix phx.server
```

This can be fixed by replacing `"method":"get"` with `"method":"GET"`. Suggestion: [convert method to uppercase when parsing](https://github.com/elixir-plug/plug/blob/master/lib/plug/router/utils.ex#L28).

---

> you can test it also manually:

I guess the JSON should be a list..

The other tests work as expected.

**Comment by mmacai** [comment]
> ```shell
> $ PROXY_CONFIG_FILE='{}' mix phx.server
> ...
> 13:14:32.063 module=gen_server [error] GenServer RigInboundGateway.Proxy terminating
> ** (MatchError) no match of right hand side value: {:error, "the proxy config must be a list", [not_a_list: %{}]}
>     (rig 2.3.0) lib/rig_inbound_gateway/proxy.ex:140: RigInboundGateway.Proxy.handle_info/2
>     (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
>     (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6
>     (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
> Last message: :init_apis
> State: %{tracker_mod: RigInboundGateway.ApiProxy.Tracker}
> ```
> 
> but keeps running - I've expected RIG to halt here. Same when using a file that doesn't exist:
> 
> ```shell
> $ PROXY_CONFIG_FILE=./doesnotexist.json mix phx.server
> ...
> 13:21:26.703 module=gen_server [error] GenServer RigInboundGateway.Proxy terminating
> ** (MatchError) no match of right hand side value: {:error, "could not read proxy config", [syntax_error: [{:not_found, "./proxy.json"}, %Jason.DecodeError{data: "./proxy.json", position: 0, token: nil}], path_or_json: "./proxy.json"]}
>     (rig 2.3.0) lib/rig_inbound_gateway/proxy.ex:140: RigInboundGateway.Proxy.handle_info/2
>     (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
>     (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6
>     (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
> Last message: :init_apis
> State: %{tracker_mod: RigInboundGateway.ApiProxy.Tracker}
> ```
> 
> Doesn't halt...
> 
> `version_data.default.endpoints` should be a list. However, when using an object instead, there are no errors reported:
> 
> ```shell
> $ PROXY_CONFIG_FILE='[{"id":"a","name":"a","proxy":{"target_url":"KAFKA_HOST","use_env":true,"port":9092},"version_data":{"default":{"endpoints":{}}}}]' mix phx.server
> ...
> 13:29:45.584 module=RigInboundGateway.ApiProxy.Tracker [info] Starting to track new API definition with id=a
> ...
> ```
> 
> The HTTP method shouldn't be parsed in a case-sensitive way. For example, this runs without warnings but doesn't work as expected:
> 
> ```shell
> PROXY_CONFIG_FILE='[{"id":"a","name":"a","proxy":{"target_url":"KAFKA_HOST","use_env":true,"port":9092},"version_data":{"default":{"endpoints":[{"id":"x","path":"/x","method":"get"}]}}}]' mix phx.server
> ```
> 
> This can be fixed by replacing `"method":"get"` with `"method":"GET"`. Suggestion: [convert method to uppercase when parsing](https://github.com/elixir-plug/plug/blob/master/lib/plug/router/utils.ex#L28).
> 
> > you can test it also manually:
> 
> I guess the JSON should be a list..
> 
> The other tests work as expected.

Everything besides http method thingy should be fixed, give it another try please.

Regarding http method parsing, where would you like to do it?

**Comment by kevinbader** [comment]
> Everything besides http method thingy should be fixed, give it another try please.

works now - thanks!

> Regarding http method parsing, where would you like to do it?

I guess `Rig.Config.parse_json_env/1` would make sense.

**Comment by mmacai** [comment]
> > Everything besides http method thingy should be fixed, give it another try please.
> 
> works now - thanks!
> 
> > Regarding http method parsing, where would you like to do it?
> 
> I guess `Rig.Config.parse_json_env/1` would make sense.

HTTP method uppercasing should be handled now (added also test for it).

**Pull request merged**
